### ISSUE TITLE
Criar layout para colaborador e dividir o de associado

### ISSUE THREAD

**Issue by reinan47** [marcosdosea/GestaoGrupoMusical#509]
Quando logar no sistema, o colaborador, não consegue acessar suas funções.(verificar, se precisar mesmo)

![Image](https://user-images.githubusercontent.com/50469065/266147132-3a129a49-ed09-4741-bbfa-5ea75d897578.png)

precisa fazer isso aqui, nas funções do colaborador

duração: 2 dias (8hrs)

**Comment by junio10** [comment]
@reinan47 já t[á implementado, @ms-daniel não viu e acabou criando outra tarefa depois, que já está feita

**Comment by junio10** [comment]
no instrumento musical controller
